airquality<-datasets::airquality
haed(airquality,5)
head(airquality,5)
summary(airquality[,3])
summary(airquality$Temp)
summ(ary(airquality$Ozone)
plot(airquality$Temp)
plot(airquality$temp
     
     
)
plot(airquality)
plot(airquality$Ozone,type= "b")
barplot(airquality$Ozone, xlab ='ozone concentration',ylab ='no of instance',main ='ozone levels in ny city',col = 'red',horiz = TRUE)
hist(airquality$Solar.R, col = 'red')
boxplot(airquality)
boxplot(airquality[,1:4])
pnorm(70,60,10)
pnorm(50,60,10)
1-pnorm(50,60,10)
pnorm((680,711,29)
pnorm(740,711,29)-pnorm(697,711,29)
qnrm(95)
1-pt(.47,49)
pt(-4.65,49)
2*pt(-4.65,49)
pt(-0.47,49)
2*pt(-0.47,49)
library("lattice")
attach(wc_at)
wc_at
WC_AT
attach(WC_AT)
dotplot(AT,main="dot plotof at circulation",col="dodgerblue")
dotplot(Waist,main="dot plotof at circulation",col="dodgerblue")
boxplot(AT,col="dodgerblue")
boxplot(Waist,col="dodgerblue")
reg.model<-lm(AT~Waist)
summary(reg.model)
